In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Datasets/IMDB Dataset.csv')

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [6]:
new_df = df.iloc[:5000]

In [10]:
new_df.shape, new_df.head(), type(new_df)

((5000, 2),
                                               review sentiment
 0  One of the other reviewers has mentioned that ...  positive
 1  A wonderful little production. <br /><br />The...  positive
 2  I thought this was a wonderful way to spend ti...  positive
 3  Basically there's a family where a little boy ...  negative
 4  Petter Mattei's "Love in the Time of Money" is...  positive,
 pandas.core.frame.DataFrame)

In [22]:
# replacing positive to 0 and negative to 1
df['sentiment'].replace({'positive':1, 'negative':0}, inplace=True)

In [23]:
df.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [24]:
new_df['sentiment'].replace({'positive':1, 'negative':0}, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_6656\4291106397.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['sentiment'].replace({'positive':1, 'negative':0}, inplace=True)

In [25]:
new_df

                                                 review  sentiment
0     One of the other reviewers has mentioned that ...          1
1     A wonderful little production. <br /><br />The...          1
2     I thought this was a wonderful way to spend ti...          1
3     Basically there's a family where a little boy ...          0
4     Petter Mattei's "Love in the Time of Money" is...          1
...                                                 ...        ...
4995  An interesting slasher film with multiple susp...          0
4996  i watched this series when it first came out i...          1
4997  Once again Jet Li brings his charismatic prese...          1
4998  I rented this movie, after hearing Chris Gore ...          0
4999  This was a big disappointment for me. I think ...          0

[5000 rows x 2 columns]

### Text Preprocessing

In [4]:
import regex as re

In [20]:
# remove html tags
def remove_tags(text):
    pattern = "<.*?>"    
    return re.sub(pattern,'',text)

In [26]:
new_df['review'] = new_df['review'].apply(remove_tags)

C:\Users\HP\AppData\Local\Temp\ipykernel_6656\2323644113.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['review'] = new_df['review'].apply(remove_tags)

In [29]:
new_df.iloc[2].review

'I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the style many of us have grown to love.This was the most I\'d laughed at one of Woody\'s comedies in years (dare I say a decade?). While I\'ve never been impressed with Scarlet Johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.This may not be the crown jewel of his career, but it was wittier than "Devil Wears Prada" and more interesting than "Superman" a great comedy to go see with friends.'

In [30]:
def convert_lower(text):
    return text.lower()

In [31]:
new_df['review']=new_df['review'].apply(convert_lower)

C:\Users\HP\AppData\Local\Temp\ipykernel_6656\526202214.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['review']=new_df['review'].apply(convert_lower)

In [32]:
new_df.iloc[3].review

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [33]:
#to remove special characters
def remove_special(text):
    pattern = re.compile("[$&+,:;=?@#|'<>.-^*()%!]")
    return re.sub(pattern,'',text)

In [34]:
new_df['review']=new_df['review'].apply(remove_special)

C:\Users\HP\AppData\Local\Temp\ipykernel_6656\3079912608.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['review']=new_df['review'].apply(remove_special)

In [35]:
new_df.iloc[3].review

'basically theres a family where a little boy jake thinks theres a zombie in his closet  his parents are fighting all the timethis movie is slower than a soap opera and suddenly jake decides to become rambo and kill the zombieok first of all when youre going to make a film you must decide if its a thriller or a drama as a drama the movie is watchable parents are divorcing  arguing like in real life and then we have jake with his closet which totally ruins all the film i expected to see a boogeyman similar movie and instead i watched a drama with some meaningless thriller spots out of  just for the well playing parents  descent dialogs as for the shots with jake just ignore them'

In [36]:
# stop word removal
import nltk

In [37]:
from nltk.corpus import stopwords

In [51]:
def remove_stopwords(text):
    clean = [i for i in text.split(' ') if i not in stopwords.words('english') and i!='']
    return clean

In [52]:
remove_stopwords(new_df.iloc[3].review)

['basically',
 'theres',
 'family',
 'little',
 'boy',
 'jake',
 'thinks',
 'theres',
 'zombie',
 'closet',
 'parents',
 'fighting',
 'timethis',
 'movie',
 'slower',
 'soap',
 'opera',
 'suddenly',
 'jake',
 'decides',
 'become',
 'rambo',
 'kill',
 'zombieok',
 'first',
 'youre',
 'going',
 'make',
 'film',
 'must',
 'decide',
 'thriller',
 'drama',
 'drama',
 'movie',
 'watchable',
 'parents',
 'divorcing',
 'arguing',
 'like',
 'real',
 'life',
 'jake',
 'closet',
 'totally',
 'ruins',
 'film',
 'expected',
 'see',
 'boogeyman',
 'similar',
 'movie',
 'instead',
 'watched',
 'drama',
 'meaningless',
 'thriller',
 'spots',
 'well',
 'playing',
 'parents',
 'descent',
 'dialogs',
 'shots',
 'jake',
 'ignore']

In [53]:
new_df['review']=new_df['review'].apply(remove_stopwords)

C:\Users\HP\AppData\Local\Temp\ipykernel_6656\2677256723.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['review']=new_df['review'].apply(remove_stopwords)

In [54]:
new_df

                                                 review  sentiment
0     [one, reviewers, mentioned, watching, oz, epis...          1
1     [wonderful, little, production, filming, techn...          1
2     [thought, wonderful, way, spend, time, hot, su...          1
3     [basically, theres, family, little, boy, jake,...          0
4     [petter, matteis, "love, time, money", visuall...          1
...                                                 ...        ...
4995  [interesting, slasher, film, multiple, suspect...          0
4996  [watched, series, first, came, si, years, old,...          1
4997  [jet, li, brings, charismatic, presence, movie...          1
4998  [rented, movie, hearing, chris, gore, saying, ...          0
4999  [big, disappointment, think, worst, mastroiann...          0

[5000 rows x 2 columns]

In [57]:
new_df.iloc[0].review

['one',
 'reviewers',
 'mentioned',
 'watching',
 'oz',
 'episode',
 'youll',
 'hooked',
 'right',
 'exactly',
 'happened',
 'methe',
 'first',
 'thing',
 'struck',
 'oz',
 'brutality',
 'unflinching',
 'scenes',
 'violence',
 'set',
 'right',
 'word',
 'go',
 'trust',
 'show',
 'faint',
 'hearted',
 'timid',
 'show',
 'pulls',
 'punches',
 'regards',
 'drugs',
 'sex',
 'violence',
 'hardcore',
 'classic',
 'use',
 'wordit',
 'called',
 'oz',
 'nickname',
 'given',
 'oswald',
 'maximum',
 'security',
 'state',
 'penitentary',
 'focuses',
 'mainly',
 'emerald',
 'city',
 'experimental',
 'section',
 'prison',
 'cells',
 'glass',
 'fronts',
 'face',
 'inwards',
 'privacy',
 'high',
 'agenda',
 'em',
 'city',
 'home',
 'manyaryans',
 'muslims',
 'gangstas',
 'latinos',
 'christians',
 'italians',
 'irish',
 'moreso',
 'scuffles',
 'death',
 'stares',
 'dodgy',
 'dealings',
 'shady',
 'agreements',
 'never',
 'far',
 'awayi',
 'would',
 'say',
 'main',
 'appeal',
 'show',
 'due',
 'fact',
 'goes',
 'shows',
 'wouldnt',
 'dare',
 'forget',
 'pretty',
 'pictures',
 'painted',
 'mainstream',
 'audiences',
 'forget',
 'charm',
 'forget',
 'romanceoz',
 'doesnt',
 'mess',
 'around',
 'first',
 'episode',
 'ever',
 'saw',
 'struck',
 'nasty',
 'surreal',
 'couldnt',
 'say',
 'ready',
 'watched',
 'developed',
 'taste',
 'oz',
 'got',
 'accustomed',
 'high',
 'levels',
 'graphic',
 'violence',
 'violence',
 'injustice',
 'crooked',
 'guards',
 'wholl',
 'sold',
 'nickel',
 'inmates',
 'wholl',
 'kill',
 'order',
 'get',
 'away',
 'well',
 'mannered',
 'middle',
 'class',
 'inmates',
 'turned',
 'prison',
 'bitches',
 'due',
 'lack',
 'street',
 'skills',
 'prison',
 'experience',
 'watching',
 'oz',
 'may',
 'become',
 'comfortable',
 'uncomfortable',
 'viewingthats',
 'get',
 'touch',
 'darker',
 'side']

In [62]:
# perform stemming
from nltk.stem import PorterStemmer
ps = PorterStemmer()
def convert_stem(text):
    stemmed = [ps.stem(i) for i in text]
    return stemmed

In [66]:
temp = convert_stem(new_df.iloc[3].review)

In [67]:
len(new_df.iloc[3].review), len(temp)

(66, 66)

In [68]:
new_df['review']=new_df["review"].apply(convert_stem)

C:\Users\HP\AppData\Local\Temp\ipykernel_6656\585748722.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['review']=new_df["review"].apply(convert_stem)

In [69]:
# join back
def join_text(stem_list):
    return ' '.join(stem_list)

In [70]:
new_df['review']=new_df['review'].apply(join_text)

C:\Users\HP\AppData\Local\Temp\ipykernel_6656\3304734311.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['review']=new_df['review'].apply(join_text)

In [71]:
new_df

                                                 review  sentiment
0     one review mention watch oz episod youll hook ...          1
1     wonder littl product film techniqu unassuming-...          1
2     thought wonder way spend time hot summer weeke...          1
3     basic there famili littl boy jake think there ...          0
4     petter mattei "love time money" visual stun fi...          1
...                                                 ...        ...
4995  interest slasher film multipl suspectsinclud t...          0
4996  watch seri first came si year old watch best f...          1
4997  jet li bring charismat presenc movi screen fil...          1
4998  rent movi hear chri gore say someth effect "fi...          0
4999  big disappoint think worst mastroianni-movi ev...          0

[5000 rows x 2 columns]

In [72]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [73]:
X=cv.fit_transform(new_df['review']).toarray()

In [74]:
X.shape

(5000, 38217)

In [82]:
X[0].max()

5

In [78]:
y = new_df.iloc[:,-1].values

In [79]:
y

array([1, 1, 1, ..., 1, 0, 0], dtype=int64)

In [80]:
y.shape

(5000,)

## ML part

In [83]:
from sklearn.model_selection import train_test_split

In [84]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [85]:
X_train.shape

(4000, 38217)

In [86]:
X_test.shape

(1000, 38217)

In [87]:
y_train.shape

(4000,)

In [88]:
y_test.shape

(1000,)

In [89]:
# Algorithm: Naive Bayes
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [90]:
clf1 = GaussianNB()
clf2 = MultinomialNB()
clf3 = BernoulliNB()

In [91]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)

BernoulliNB()

In [93]:
y_pred_1 = clf1.predict(X_test)
y_pred_2 = clf2.predict(X_test)
y_pred_3 = clf3.predict(X_test)

In [94]:
y_pred_1.shape

(1000,)

In [95]:
# Accuracy
from sklearn.metrics import accuracy_score

In [96]:
print("Gaussian: ", accuracy_score(y_test, y_pred_1))
print("Multinomial: ", accuracy_score(y_test, y_pred_2))
print("Bernaulli: ", accuracy_score(y_test, y_pred_3))

Gaussian:  0.634
Multinomial:  0.831
Bernaulli:  0.841