In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Datasets/IMDB Dataset.csv')

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  str
 1   sentiment  50000 non-null  str
dtypes: str(2)
memory usage: 781.4 KB

In [5]:
new_df = df.iloc[:5000]

In [6]:
new_df.shape, new_df.head(), type(new_df)

((5000, 2),
                                               review sentiment
 0  One of the other reviewers has mentioned that ...  positive
 1  A wonderful little production. <br /><br />The...  positive
 2  I thought this was a wonderful way to spend ti...  positive
 3  Basically there's a family where a little boy ...  negative
 4  Petter Mattei's "Love in the Time of Money" is...  positive,
 pandas.DataFrame)

In [7]:
# replacing positive to 0 and negative to 1
df['sentiment'].replace({'positive':1, 'negative':0}, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_8508\987798682.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['sentiment'].replace({'positive':1, 'negative':0}, inplace=True)

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 50000, dtype: object

In [8]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [9]:
new_df['sentiment'].replace({'positive':1, 'negative':0}, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_8508\4291106397.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  new_df['sentiment'].replace({'positive':1, 'negative':0}, inplace=True)

0       1
1       1
2       1
3       0
4       1
       ..
4995    0
4996    1
4997    1
4998    0
4999    0
Name: sentiment, Length: 5000, dtype: object

In [10]:
new_df

                                                 review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. <br /><br />The...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
4995  An interesting slasher film with multiple susp...  negative
4996  i watched this series when it first came out i...  positive
4997  Once again Jet Li brings his charismatic prese...  positive
4998  I rented this movie, after hearing Chris Gore ...  negative
4999  This was a big disappointment for me. I think ...  negative

[5000 rows x 2 columns]

### Text Preprocessing

In [11]:
import regex as re

In [12]:
# remove html tags
def remove_tags(text):
    pattern = "<.*?>"    
    return re.sub(pattern,'',text)

In [13]:
new_df['review'] = new_df['review'].apply(remove_tags)

In [14]:
new_df.iloc[2].review

'I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the style many of us have grown to love.This was the most I\'d laughed at one of Woody\'s comedies in years (dare I say a decade?). While I\'ve never been impressed with Scarlet Johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.This may not be the crown jewel of his career, but it was wittier than "Devil Wears Prada" and more interesting than "Superman" a great comedy to go see with friends.'

In [15]:
def convert_lower(text):
    return text.lower()

In [16]:
new_df['review']=new_df['review'].apply(convert_lower)

In [17]:
new_df.iloc[3].review

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [18]:
#to remove special characters
def remove_special(text):
    pattern = re.compile("[$&+,:;=?@#|'<>.-^*()%!]")
    return re.sub(pattern,'',text)

In [19]:
new_df['review']=new_df['review'].apply(remove_special)

In [20]:
new_df.iloc[3].review

'basically theres a family where a little boy jake thinks theres a zombie in his closet  his parents are fighting all the timethis movie is slower than a soap opera and suddenly jake decides to become rambo and kill the zombieok first of all when youre going to make a film you must decide if its a thriller or a drama as a drama the movie is watchable parents are divorcing  arguing like in real life and then we have jake with his closet which totally ruins all the film i expected to see a boogeyman similar movie and instead i watched a drama with some meaningless thriller spots out of  just for the well playing parents  descent dialogs as for the shots with jake just ignore them'

In [21]:
# stop word removal
import nltk

In [22]:
from nltk.corpus import stopwords

In [23]:
def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))
    processed = [word for word in text.split() if word not in stop_words]
    return processed

In [24]:
remove_stopwords(new_df.iloc[3].review)

['basically',
 'theres',
 'family',
 'little',
 'boy',
 'jake',
 'thinks',
 'theres',
 'zombie',
 'closet',
 'parents',
 'fighting',
 'timethis',
 'movie',
 'slower',
 'soap',
 'opera',
 'suddenly',
 'jake',
 'decides',
 'become',
 'rambo',
 'kill',
 'zombieok',
 'first',
 'youre',
 'going',
 'make',
 'film',
 'must',
 'decide',
 'thriller',
 'drama',
 'drama',
 'movie',
 'watchable',
 'parents',
 'divorcing',
 'arguing',
 'like',
 'real',
 'life',
 'jake',
 'closet',
 'totally',
 'ruins',
 'film',
 'expected',
 'see',
 'boogeyman',
 'similar',
 'movie',
 'instead',
 'watched',
 'drama',
 'meaningless',
 'thriller',
 'spots',
 'well',
 'playing',
 'parents',
 'descent',
 'dialogs',
 'shots',
 'jake',
 'ignore']

In [25]:
new_df['review']=new_df['review'].apply(remove_stopwords)

In [26]:
new_df

                                                 review sentiment
0     [one, reviewers, mentioned, watching, oz, epis...  positive
1     [wonderful, little, production, filming, techn...  positive
2     [thought, wonderful, way, spend, time, hot, su...  positive
3     [basically, theres, family, little, boy, jake,...  negative
4     [petter, matteis, "love, time, money", visuall...  positive
...                                                 ...       ...
4995  [interesting, slasher, film, multiple, suspect...  negative
4996  [watched, series, first, came, si, years, old,...  positive
4997  [jet, li, brings, charismatic, presence, movie...  positive
4998  [rented, movie, hearing, chris, gore, saying, ...  negative
4999  [big, disappointment, think, worst, mastroiann...  negative

[5000 rows x 2 columns]

In [27]:
new_df.iloc[0].review

['one',
 'reviewers',
 'mentioned',
 'watching',
 'oz',
 'episode',
 'youll',
 'hooked',
 'right',
 'exactly',
 'happened',
 'methe',
 'first',
 'thing',
 'struck',
 'oz',
 'brutality',
 'unflinching',
 'scenes',
 'violence',
 'set',
 'right',
 'word',
 'go',
 'trust',
 'show',
 'faint',
 'hearted',
 'timid',
 'show',
 'pulls',
 'punches',
 'regards',
 'drugs',
 'sex',
 'violence',
 'hardcore',
 'classic',
 'use',
 'wordit',
 'called',
 'oz',
 'nickname',
 'given',
 'oswald',
 'maximum',
 'security',
 'state',
 'penitentary',
 'focuses',
 'mainly',
 'emerald',
 'city',
 'experimental',
 'section',
 'prison',
 'cells',
 'glass',
 'fronts',
 'face',
 'inwards',
 'privacy',
 'high',
 'agenda',
 'em',
 'city',
 'home',
 'manyaryans',
 'muslims',
 'gangstas',
 'latinos',
 'christians',
 'italians',
 'irish',
 'moreso',
 'scuffles',
 'death',
 'stares',
 'dodgy',
 'dealings',
 'shady',
 'agreements',
 'never',
 'far',
 'awayi',
 'would',
 'say',
 'main',
 'appeal',
 'show',
 'due',
 'fact',
 'goes',
 'shows',
 'wouldnt',
 'dare',
 'forget',
 'pretty',
 'pictures',
 'painted',
 'mainstream',
 'audiences',
 'forget',
 'charm',
 'forget',
 'romanceoz',
 'doesnt',
 'mess',
 'around',
 'first',
 'episode',
 'ever',
 'saw',
 'struck',
 'nasty',
 'surreal',
 'couldnt',
 'say',
 'ready',
 'watched',
 'developed',
 'taste',
 'oz',
 'got',
 'accustomed',
 'high',
 'levels',
 'graphic',
 'violence',
 'violence',
 'injustice',
 'crooked',
 'guards',
 'wholl',
 'sold',
 'nickel',
 'inmates',
 'wholl',
 'kill',
 'order',
 'get',
 'away',
 'well',
 'mannered',
 'middle',
 'class',
 'inmates',
 'turned',
 'prison',
 'bitches',
 'due',
 'lack',
 'street',
 'skills',
 'prison',
 'experience',
 'watching',
 'oz',
 'may',
 'become',
 'comfortable',
 'uncomfortable',
 'viewingthats',
 'get',
 'touch',
 'darker',
 'side']

In [28]:
# perform stemming
from nltk.stem import PorterStemmer
ps = PorterStemmer()
def convert_stem(text):
    stemmed = [ps.stem(i) for i in text]
    return stemmed

In [29]:
temp = convert_stem(new_df.iloc[3].review)

In [30]:
len(new_df.iloc[3].review), len(temp)

(66, 66)

In [31]:
stemmed_df = pd.DataFrame()

In [32]:
stemmed_df['review']=new_df["review"].apply(convert_stem)

In [33]:
stemmed_df['sentiment'] = new_df['sentiment']

In [34]:
stemmed_df.head()

                                              review sentiment
0  [one, review, mention, watch, oz, episod, youl...  positive
1  [wonder, littl, product, film, techniqu, unass...  positive
2  [thought, wonder, way, spend, time, hot, summe...  positive
3  [basic, there, famili, littl, boy, jake, think...  negative
4  [petter, mattei, "love, time, money", visual, ...  positive

In [35]:
stemmed_df['sentiment'] = stemmed_df['sentiment'].replace({'positive':1, 'negative':0},inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_8508\2266989832.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  stemmed_df['sentiment'] = stemmed_df['sentiment'].replace({'positive':1, 'negative':0},inplace=True)

In [36]:
stemmed_df['sentiment']

0       1
1       1
2       1
3       0
4       1
       ..
4995    0
4996    1
4997    1
4998    0
4999    0
Name: sentiment, Length: 5000, dtype: object

In [37]:
# join back
def join_text(stem_list):
    return ' '.join(stem_list)

In [38]:
stemmed_df['review']=stemmed_df['review'].apply(join_text)

In [39]:
stemmed_df

                                                 review sentiment
0     one review mention watch oz episod youll hook ...         1
1     wonder littl product film techniqu unassuming-...         1
2     thought wonder way spend time hot summer weeke...         1
3     basic there famili littl boy jake think there ...         0
4     petter mattei "love time money" visual stun fi...         1
...                                                 ...       ...
4995  interest slasher film multipl suspectsinclud t...         0
4996  watch seri first came si year old watch best f...         1
4997  jet li bring charismat presenc movi screen fil...         1
4998  rent movi hear chri gore say someth effect "fi...         0
4999  big disappoint think worst mastroianni-movi ev...         0

[5000 rows x 2 columns]

In [40]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [41]:
X=cv.fit_transform(stemmed_df['review']).toarray()

In [42]:
X.shape

(5000, 38196)

In [43]:
X[0].max()

np.int64(5)

In [44]:
y = stemmed_df.iloc[:,-1].values

In [45]:
y

array([1, 1, 1, ..., 1, 0, 0], shape=(5000,), dtype=object)

In [46]:
y.shape

(5000,)

## ML part

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [49]:
X_train.shape

(4000, 38196)

In [50]:
X_test.shape

(1000, 38196)

In [51]:
y_train.shape

(4000,)

In [52]:
y_test.shape

(1000,)

In [56]:
y_train

array([0, 0, 1, ..., 0, 1, 0], shape=(4000,), dtype=object)

In [57]:
y_train = y_train.astype("int64")
y_test = y_test.astype("int64")

In [61]:
y_train

array([0, 0, 1, ..., 0, 1, 0], shape=(4000,))

In [58]:
# Algorithm: Naive Bayes
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [59]:
clf1 = GaussianNB()
clf2 = MultinomialNB()
clf3 = BernoulliNB()

In [60]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)

BernoulliNB()

In [62]:
y_pred_1 = clf1.predict(X_test)
y_pred_2 = clf2.predict(X_test)
y_pred_3 = clf3.predict(X_test)

In [63]:
y_pred_1.shape

(1000,)

In [64]:
# Accuracy
from sklearn.metrics import accuracy_score

In [65]:
print("Gaussian: ", accuracy_score(y_test, y_pred_1))
print("Multinomial: ", accuracy_score(y_test, y_pred_2))
print("Bernaulli: ", accuracy_score(y_test, y_pred_3))

Gaussian:  0.633
Multinomial:  0.829
Bernaulli:  0.841

In [77]:
new_text = ["This movie was absolutely amazing"]

In [78]:
new_text = convert_lower(new_text[0])

In [79]:
new_text

'this movie was absolutely amazing'

In [80]:
new_text = remove_stopwords(new_text)
new_text

['movie', 'absolutely', 'amazing']

In [81]:
new_text = convert_stem(new_text)

In [82]:
new_text

['movi', 'absolut', 'amaz']

In [83]:
new_text = join_text(new_text)
new_text

'movi absolut amaz'

In [86]:
text_list = []

In [87]:
text_list.append(new_text)
text_list

['movi absolut amaz']

In [88]:
new_vector = cv.transform(text_list)

In [89]:
new_vector.shape

(1, 38196)

In [90]:
prediction = clf3.predict(new_vector)
print(prediction)

[1]

In [110]:
sample_text = input('Enter a review')
sample_text

'The movie was not good.'

In [111]:
sample_text = convert_lower(sample_text[0])
sample_text = remove_stopwords(sample_text)
sample_text = convert_stem(sample_text)
sample_text = join_text(sample_text)
sample_text_list = []
sample_text_list.append(sample_text)
new_vector = cv.transform(sample_text_list)
new_vector.shape

(1, 38196)

In [112]:
sample_pred = clf3.predict(new_vector)
print(sample_pred)

[1]

In [113]:
print(np.unique(y_train, return_counts=True))

(array([0, 1]), array([2024, 1976]))

**TF-IDF**

In [114]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [120]:
stop_words = list(stopwords.words('english'))

In [129]:
v1 = TfidfVectorizer(stop_words=stop_words)

In [116]:
v2 = TfidfVectorizer(max_features=500)

In [131]:
new_df['review'] = new_df['review'].apply(join_text)
new_df['review']

0       one reviewers mentioned watching oz episode yo...
1       wonderful little production filming technique ...
2       thought wonderful way spend time hot summer we...
3       basically theres family little boy jake thinks...
4       petter matteis "love time money" visually stun...
                              ...
4995    interesting slasher film multiple suspectsincl...
4996    watched series first came si years old watched...
4997    jet li brings charismatic presence movie scree...
4998    rented movie hearing chris gore saying somethi...
4999    big disappointment think worst mastroianni-mov...
Name: review, Length: 5000, dtype: str

In [132]:
X1 = v1.fit_transform(new_df['review'])

In [124]:
X2 = v2.fit_transform(stemmed_df['review'])

In [125]:
X2.shape

(5000, 500)

In [ ]:
v2.get_feature_names_out()

array(['abl', 'absolut', 'act', 'action', 'actor', 'actress', 'actual',
       'add', 'age', 'almost', 'along', 'alreadi', 'also', 'although',
       'alway', 'amaz', 'american', 'anim', 'annoy', 'anoth', 'anyon',
       'anyth', 'appar', 'appear', 'around', 'art', 'ask', 'attempt',
       'audienc', 'aw', 'away', 'back', 'bad', 'base', 'basic', 'beauti',
       'becom', 'begin', 'behind', 'believ', 'best', 'better', 'big',
       'bit', 'black', 'bodi', 'book', 'bore', 'boy', 'brilliant',
       'bring', 'brother', 'budget', 'call', 'came', 'camera', 'cant',
       'car', 'care', 'case', 'cast', 'certainli', 'chanc', 'chang',
       'charact', 'child', 'children', 'cinema', 'citi', 'classic',
       'close', 'come', 'comedi', 'comic', 'comment', 'complet', 'consid',
       'continu', 'could', 'couldnt', 'coupl', 'cours', 'creat', 'credit',
       'critic', 'cut', 'danc', 'dark', 'daughter', 'day', 'dead', 'deal',
       'death', 'decent', 'decid', 'definit', 'deserv', 'despit',
       'develop', 'dialogu', 'didnt', 'die', 'differ', 'direct',
       'director', 'disappoint', 'doesnt', 'done', 'dont', 'drama', 'dvd',
       'earli', 'edit', 'effect', 'either', 'element', 'els', 'emot',
       'end', 'english', 'enjoy', 'enough', 'entertain', 'entir',
       'episod', 'especi', 'even', 'event', 'ever', 'everi', 'everyon',
       'everyth', 'evil', 'exampl', 'excel', 'except', 'expect', 'experi',
       'extrem', 'eye', 'face', 'fact', 'fail', 'fall', 'famili', 'fan',
       'far', 'father', 'favorit', 'featur', 'feel', 'felt', 'fight',
       'figur', 'film', 'final', 'find', 'fine', 'first', 'flick',
       'follow', 'forc', 'found', 'friend', 'full', 'fun', 'funni',
       'game', 'gave', 'gener', 'genr', 'get', 'girl', 'give', 'given',
       'go', 'god', 'goe', 'good', 'got', 'great', 'group', 'guess',
       'guy', 'half', 'hand', 'happen', 'hard', 'hate', 'he', 'head',
       'heard', 'heart', 'hell', 'help', 'hero', 'high', 'highli',
       'histori', 'hit', 'hollywood', 'home', 'hope', 'horribl', 'horror',
       'hour', 'hous', 'howev', 'huge', 'human', 'humor', 'id', 'idea',
       'ill', 'im', 'imagin', 'import', 'impress', 'includ', 'incred',
       'instead', 'interest', 'involv', 'isnt', 'ive', 'job', 'john',
       'joke', 'keep', 'kid', 'kill', 'killer', 'kind', 'know', 'known',
       'lack', 'last', 'late', 'later', 'laugh', 'lead', 'learn', 'least',
       'leav', 'left', 'less', 'let', 'level', 'life', 'light', 'like',
       'line', 'littl', 'live', 'long', 'look', 'lost', 'lot', 'love',
       'low', 'made', 'main', 'major', 'make', 'man', 'manag', 'mani',
       'matter', 'may', 'mayb', 'mean', 'meet', 'men', 'mention',
       'michael', 'might', 'mind', 'minut', 'miss', 'moment', 'money',
       'monster', 'mother', 'move', 'movi', 'mr', 'much', 'murder',
       'music', 'must', 'mysteri', 'name', 'natur', 'need', 'never',
       'new', 'next', 'nice', 'night', 'noth', 'novel', 'number',
       'obvious', 'offer', 'often', 'oh', 'old', 'one', 'open', 'order',
       'origin', 'other', 'overal', 'part', 'past', 'peopl', 'perfect',
       'perform', 'perhap', 'person', 'pictur', 'piec', 'place', 'play',
       'plot', 'point', 'polic', 'poor', 'portray', 'possibl', 'power',
       'present', 'pretti', 'probabl', 'problem', 'produc', 'product',
       'put', 'qualiti', 'question', 'quit', 'rate', 'rather', 'read',
       'real', 'realiz', 'realli', 'reason', 'recommend', 'relationship',
       'releas', 'rememb', 'rent', 'rest', 'return', 'review', 'ridicul',
       'right', 'robert', 'rock', 'role', 'run', 'said', 'save', 'saw',
       'say', 'scene', 'school', 'score', 'screen', 'script', 'second',
       'see', 'seem', 'seen', 'sens', 'sequenc', 'seri', 'set', 'sever',
       'sex', 'she', 'shoot', 'short', 'shot', 'show', 'side', 'simpli',
       'sinc', 'sit', 'situat', 'slow', 'small', 'someon', 'someth',
       'sometim', 'son', 'song', 'soon', 'sort', 'sound', 'special',
       'stand', 'star', 'start', 'stay', 'still', 'stop', 'stori',
       'stuff', 'stupid', 'style', 'success', 'support', 'suppos', 'sure',
       'surpris', 'take', 'talent', 'talk', 'tell', 'terribl', 'th',
       'that', 'the', 'theme', 'there', 'theyr', 'thing', 'think',
       'though', 'thought', 'three', 'throughout', 'time', 'titl',
       'today', 'togeth', 'told', 'took', 'top', 'total', 'touch', 'town',
       'tri', 'true', 'truli', 'turn', 'tv', 'twist', 'two', 'type',
       'understand', 'unfortun', 'up', 'us', 'use', 'usual', 'version',
       'video', 'view', 'viewer', 'voic', 'wait', 'walk', 'want', 'war',
       'wasnt', 'wast', 'watch', 'way', 'well', 'went', 'what', 'white',
       'whole', 'wife', 'wish', 'without', 'woman', 'women', 'wonder',
       'wont', 'word', 'work', 'world', 'wors', 'worst', 'worth', 'would',
       'write', 'writer', 'written', 'wrong', 'ye', 'year', 'yet',
       'youll', 'young', 'your'], dtype=object)

In [133]:
X1.shape

(5000, 49775)

**Test-Train**

In [134]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1,y,test_size=0.2,random_state=2)

In [135]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2,y,test_size=0.2,random_state=2)

In [136]:
X1_train.shape, X1_test.shape

((4000, 49775), (1000, 49775))

In [137]:
y1_train.shape, y1_test.shape

((4000,), (1000,))

In [138]:
X2_train.shape, X2_test.shape

((4000, 500), (1000, 500))

In [139]:
y2_train.shape, y2_test.shape

((4000,), (1000,))

In [144]:
y1_train = y1_train.astype("int64")
y1_test  = y1_test.astype("int64")
y2_train = y2_train.astype("int64")
y2_test  = y2_test.astype("int64")

**Model**

In [140]:
from sklearn.tree import DecisionTreeClassifier

In [145]:
model1 = DecisionTreeClassifier(max_depth=20, random_state=2)
model1.fit(X1_train, y1_train)

DecisionTreeClassifier(max_depth=20, random_state=2)

In [148]:
model2 = DecisionTreeClassifier(max_depth=20, random_state=2)
model2.fit(X2_train, y2_train)

DecisionTreeClassifier(max_depth=20, random_state=2)

In [146]:
y_pred_m1 = model1.predict(X1_test)
print("Test Accuracy:", accuracy_score(y1_test, y_pred_m1))

Test Accuracy: 0.714

In [149]:
y_pred_m2 = model2.predict(X2_test)
print("Test Accuracy:", accuracy_score(y2_test, y_pred_m2))

Test Accuracy: 0.687

In [150]:
from sklearn.ensemble import RandomForestClassifier

In [151]:
model3 = RandomForestClassifier(n_estimators=100, random_state=42)
model3.fit(X2_train, y2_train)
predictions = model3.predict(X2_test)
print("Accuracy:", accuracy_score(y2_test, predictions))

Accuracy: 0.811

In [159]:
test_1 = input()
test_1

'Visually stunning but the story felt predictable and stretched out'

In [160]:
v1_test_1 = []
v1_test_1.append(test_1)

In [161]:
v1_test_1 = v1.transform(v1_test_1)
pred_1 = model1.predict(v1_test_1)
pred_1

array([1])